### ISSUE TITLE
Provide an example of configuring the component in homeassistant

### ISSUE THREAD

**Issue by badrobit** [dotKrad/hass-fpl#1]
**Is your feature request related to a problem? Please describe.**
It would be helpful to have an example for how to set this up in the `configuration.yaml`

**Describe the solution you'd like**
Add an example section to the projects `README.md`

**Describe alternatives you've considered**
Tried setting it up myself not sure what to do.

**Additional context**
None.

**Comment by dotKrad** [comment]
the configuration is done via the frontend
In the HA UI go to "Configuration" -> "Integrations" click "+" and search for "Florida Power & Light"
