### ISSUE TITLE
Attributes Missing for Daily Usage

### ISSUE THREAD

**Issue by dorgan** [dotKrad/hass-fpl#14]
## Version of the custom_component
N/A

## Configuration
N/A

## Describe the bug
Daily Usage Attributes are missing from the Daily Usage entities, i have check both the Daily Usage KWH and Daily Usage sensors

## Debug log
N/A

![Screen Shot 2021-07-14 at 11 36 47 AM](https://user-images.githubusercontent.com/464851/125651667-edbbe534-803a-4d8a-89c5-9d362e90b5e2.png)
![Screen Shot 2021-07-14 at 11 33 09 AM](https://user-images.githubusercontent.com/464851/125651670-b6e93a73-d17c-40f4-a533-7f65a1f2470a.png)

**Comment by dotKrad** [comment]
we decided instead of using attributes to store the history of the daily usage, users can use the home assistant history mechanism, logbook and record for it
