### ISSUE TITLE
I am trying to use the data provided by your FPL addon in my own energy dashboards.

### ISSUE THREAD

**Issue by dotKrad** [dotKrad/hass-fpl#17]
Hi there.  I am wondering if my request is related to this one.  I am trying to use the data provided by your FPL addon in my own energy dashboards.  I have the Prometheus addon setup to scrape the data from Home Assistant, then the Grafana addon will put the data into nice looking graphs, but the way the data attributes are setup currently, the data cannot be read into Prometheus.  The issues appears to be the attributes: "This data is provided by FPL. integration: FPL".

Other sensors that can be read by Prometheus say something similar to:
state_class: measurement
unit_of_measurement: kWh
friendly_name: Energy Usage Total 1month
device_class: energy

I would LOVE to be able to use the date fields from the FPL addon in Grafana as well to display current billing and next billing dates, but have struggled to get them into a format that can be read by Prometheus as well. In reading the docs for Prometheus, it appears the date field has to either be in a Unix format or Epoch (I don't know enough to be knowledgeable) how this needs to be formatted, but haven't been able to figure out how to template this data.

I have been using a custom template for converting the dollar amount into a readable field in the configuration.yaml:
 
`sensor:
  - platform: template
    sensors:
        power_1516_monthly_usage_estimate:
        friendly_name: "1516 Current Monthly Usage Dollars Estimate"
        unit_of_measurement: '$'
        icon_template: mdi:currency-usd
        value_template: "{{ ((states('sensor.fpl_xxxxxxxxx_bill_to_date_kwh') |float) *0.1235) }}"   `     

and this has been working well for me.  I will continue to see if I can re-format the data myself, in a custom template, but would be awesome if the data were available in a database readable format straight from the addon itself.  Thank you for providing this tool!  As is, It has been VERY helpful for me.
![Energy Dashboard](https://user-images.githubusercontent.com/29762174/130639947-32d433da-9f37-4858-aa88-c7c51fab7920.jpg)

_Originally posted by @robtheone in https://github.com/dotKrad/hass-fpl/issues/16#issuecomment-904717073_

**Comment by robtheone** [comment]
For this issue, I can say that the addon date fields are correctly formatted and read by Home Assistant.  There are no issues with the addon itself.  I incorrectly assumed there was a formatting issue which is why the dates weren't being read correctly, however that has not proven to be true.  I have had some success in getting the data moved from the addon into a database, readable by grafana, but have more work to do on my end.  You can mark this issue as closed.  Thanks
