### ISSUE TITLE
Installed and integration creation was successful but no sensors

### ISSUE THREAD

**Issue by boblisky** [dotKrad/hass-fpl#2]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
I added the files correctly to config/custom_components/fpl
I put my username and password when adding the integration and it was successful. But after a restart there is not any fpl sensors. The logs says this: 
File "/config/custom_components/fpl/sensor.py", line 66, in state
    return self._data["bill_to_date"]
TypeError: 'NoneType' object is not subscriptable

## Debug log

```text

Add your logs here.

```

**Comment by dotKrad** [comment]
are u using the last version ?

**Comment by boblisky** [comment]
I downloaded it on Saturday Feb 8th.

**Comment by boblisky** [comment]
I removed my integration and deleted the files in my custom_components and then reinstalled through HACS today.  Setting up the integration was successful, but still get this same error.

Log Details (ERROR)
Tue Feb 11 2020 14:10:05 GMT-0500 (Eastern Standard Time)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/fpl/sensor.py", line 66, in state
    return self._data["bill_to_date"]
TypeError: 'NoneType' object is not subscriptable

**Comment by dotKrad** [comment]
is your account a "Time of Use" one ? 
sorry for the inconvenient, but fpl doesn't provide a public api so am trying to reverse engineering this.

**Comment by boblisky** [comment]
I completely understand the reverse engineering no problem. I hope I can help.
I am not sure how to know if I am "time of use", but I am enrolled in net metering because I have solar panels.

**Comment by dotKrad** [comment]
I'm sorry @boblisky but i cannot figure out what's going on, i don't have enough data to test

**Comment by cjluther** [comment]
I had a similar issue but I'm not seeing anything in the logs. I was able to test out your code locally by cloning the repo and was able to make the API calls successfully, which makes me think it has something to do with the sensor integration. 

Do you know if the fact that my local instance does not have SSL may be causing an issue with the requests?

**Comment by dotKrad** [comment]
I dont think so, i dont have SSL neither.

**Comment by cjluther** [comment]
Ignore me. I’m dumb. The sensor exists I just didn’t see it listed under the integration so it confused me, but when I search entities I see it.

**Comment by dotKrad** [comment]
The sensor is now listed in the integration view, please test it.
