### ISSUE TITLE
Error fetching data

### ISSUE THREAD

**Issue by zoopster** [dotKrad/hass-fpl#25]
I'm getting an error when this custom integration starts..." Error fetching data" . Very generic, but not being a great developer, I'm not sure how to work around it.

Where can I start to troubleshoot?

`https://www.fpl.com/api/resources/account/{account}/projectedBill?premiseNumber={premise}&lastBilledDate={lastBillDate}`
The 'lastBilledDate' doesn't exist in the current api only nextBillDate and currentBillDate

What am I missing?

**Comment by zoopster** [comment]
Must be a different issue...I removed and re-added the integration and it's now not validating my credentials.

**Comment by cjluther** [comment]
I am getting "unknown error occurred" when trying to login to account as part of setting up the integration

**Comment by zoopster** [comment]
Going to close this as stale and does seem to be working just fine
