### ISSUE TITLE
Allow Custom Entity Overrides

### ISSUE THREAD

**Issue by brianberg** [dotKrad/hass-fpl#3]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Re-add `unique_id` property to sensor

**Describe alternatives you've considered**
The Home Assistant UI suggests the need for a unique ID in order to support custom entity settings. Is there a particular reason the `unique_id` was removed? What's the advantage to keeping this entity read-only?

**Additional context**

<img width="497" alt="Screen Shot 2020-06-16 at 1 47 06 PM" src="https://user-images.githubusercontent.com/5121741/84809319-e602e400-afd7-11ea-9a89-9e19ee1e1dea.png">

**Comment by dotKrad** [comment]
I was using a wrong method to create the unique id, therefore the integration was creating different sensors every time it restart, re-added the unique id again, please test it

**Comment by brianberg** [comment]
Latest changes fixed it 🎉
