### ISSUE TITLE
Missing details in the readme file for HACS usage

### ISSUE THREAD

**Issue by bcjmk** [dotKrad/hass-fpl#41]
- Compatible with HACS section missing details on usage
- Need to identify adding a custom component as many HA users are newbies
- this will serve as training aid and may increase usaage
- 
## Configuration

No configuration updates required

Add your logs here.

No logging required

## Describe the bug
Lack of information in usage section

## Debug log

```text

Add your logs here.

```

**Comment by dotKrad** [comment]
Please take a look at the updated readme and close the issue if valid

**Comment by bcjmk** [comment]
I made a number of updates and have images to share. I'm not much of a coder, but happy to help with documentation. Please review and let me know if acceptable.

Thanks,
Bill

![GitURL](https://github.com/dotKrad/hass-fpl/assets/39830560/c2553ca1-bf8a-45d7-9508-1ee3c8cfd81c)
![Custom_Repos](https://github.com/dotKrad/hass-fpl/assets/39830560/efc90b38-dae9-49d7-9a17-e7cdf48849a5)
[README.md](https://github.com/dotKrad/hass-fpl/files/11992419/README.md)

**Comment by dotKrad** [comment]
I didn't add any images, since the process to add a custom repository to HACS is already explained in the link I added

**Comment by bcjmk** [comment]
Agreed. I missed the DRY opportunity in the HACS documentation

Sent via iPhone. It's interpretation may vary from my intent.

On Jul 9, 2023, at 00:39, dotKrad ***@***.***> wrote:

﻿

I didn't add any images, since the process to add a custom repository to HACS is already explained in the link I added
