### ISSUE TITLE
Ability to have sensors to graph data

### ISSUE THREAD

**Issue by dorgan** [dotKrad/hass-fpl#6]
Currently the way the daily usage attributes are setup there is no way to ingest/use this data in a graph within homeassistant

**Comment by dotKrad** [comment]
I just put it there cause a suggestion from another user, if you want I can change the way its stored

**Comment by Lukejb14** [comment]
If the attributes were each an individual sensor, (like projected bill sensor, avg daily sensor etc.) a user can group them together manually if they wanted to have all attributes together.

**Comment by dotKrad** [comment]
I created 3 separated sensors, Projected bill, average daily and daily usage, with this one only showing the las usage day
if you need anything else pls let me know, I made this integration to fit my own need but I'm happy others are using it so I'm willing to change it to fit our needs

**Comment by dorgan** [comment]
@dotKrad I just updated and the integration is now busted.  HA versions 0.117.1.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/fpl/sensor.py", line 41, in async_setup_entry
    for account in accounts:
TypeError: 'NoneType' object is not iterable`

**Comment by dotKrad** [comment]
Please try to remove and readd the integration, and let me know

**Comment by dorgan** [comment]
@dotKrad same error after a removal, restart, install, restart

**Comment by dotKrad** [comment]
I mean, did you removed the integration in the Integrations page ?
