### ISSUE TITLE
Data not being pulled in

### ISSUE THREAD

**Issue by dorgan** [dotKrad/hass-fpl#8]
## Version of the custom_component
Current Version

## Describe the bug
Plugin does not seem to be pulling data from FPL on its own.   Each morning I must manually reload the plugin at which point the data is pulled in

**Comment by dorgan** [comment]
This is still an issue

**Comment by dotKrad** [comment]
Last night I reworked the component using the coordinator "thing" in Home Assistant to pull data, give it a try and let me know

**Comment by dorgan** [comment]
Trying a clean install and going through config, and his is what I am
getting.

**Comment by dotKrad** [comment]
try updating the custom component and let me know pls

**Comment by dorgan** [comment]
Again clean install removing customer_components/fpl/ and getting the same
error.

**Comment by dotKrad** [comment]
whats the error ?

**Comment by dorgan** [comment]
It's in the screenshot I posted.  Looking in the logs I see this:

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/fpl/config_flow.py:93
Integration: FPL (documentation)
First occurred: 7:00:28 PM (5 occurrences)
Last logged: 10:04:03 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py",
line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line
499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py",
line 119, in impl
    return await handler(request)
  File
"/usr/src/homeassistant/homeassistant/components/http/security_filter.py",
line 56, in security_filter_middleware
    return await handler(request)
  File
"/usr/src/homeassistant/homeassistant/components/http/request_context.py",
line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line
74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line
135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line
131, in handle
    result = await result
  File
"/usr/src/homeassistant/homeassistant/components/config/config_entries.py",
line 128, in post
    return await super().post(request)
  File
"/usr/src/homeassistant/homeassistant/components/http/data_validator.py",
line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py",
line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 150,
in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 176,
in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data,
init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 257,
in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/fpl/config_flow.py", line 81, in
async_step_user
    return await self._show_config_form(user_input)
  File "/config/custom_components/fpl/config_flow.py", line 93, in
_show_config_form
    data_schema[vol.Required(CONF_USERNAME, default=username)] = str
UnboundLocalError: local variable 'username' referenced before assignment

**Comment by dotKrad** [comment]
i think i resolved that issue with las update

**Comment by dorgan** [comment]
The integration now loads, but there is no data for the entities.

**Comment by dotKrad** [comment]
Check the entities in the integrations page or check the logs please

**Comment by dorgan** [comment]
Ok looks like it's working, but I used to be able to click on the entities and see the usage data for each day, seems that is now missing

**Comment by dorgan** [comment]
Looks like the entity called fpl_{account_number} is no longer created.  Most of the other data exists in other entities now, but not the daily usage data.  Not a big deal, but tapping on the entity to see daily usage is convient

**Comment by dotKrad** [comment]
That data it's now in the daily usage sensor, that sensor gives you the
last usage and in the attributes it's the list of usage  by day

**Comment by dorgan** [comment]
Excellent, thanks for the work on this.  I am now squared away.
